name: Release to Maven Central
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to use to release from."
        required: true
        default: "main"
jobs:
  release:
    name: Release to Maven Central
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.event.inputs.branch }}
        token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
        java-package: jdk
        server-id: central
        server-username: SONATYPE_USERNAME
        server-password: SONATYPE_PASSWORD
        gpg-private-key: ${{ secrets.HCOM_GPG_PRIVATE_KEY }}
        gpg-passphrase: GPG_PASSPHRASE
        settings-path: ${{ github.workspace }}

    - name: Configure Git User
      run: |
        git config user.email "oss@expediagroup.com"
        git config user.name "eg-oss-ci"

    - name: Install Local Dependencies
      run: |
          lib/install_local_libs.sh

    - name: Run Maven Targets
      run: mvn release:prepare release:perform --settings $GITHUB_WORKSPACE/settings.xml -DskipTests -Darguments=-DskipTests --activate-profiles sonatype-oss-release-github-actions --batch-mode --show-version --no-transfer-progress
      env:
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        GPG_PASSPHRASE: ${{secrets.HCOM_GPG_PRIVATE_KEY_PASSPHRASE}}
